name: going_dutch_ui
description: "Going Dutch UI"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  bloc: ^9.1.0
  collection: ^1.19.1
  fluent_ui: ^4.13.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  freezed_annotation: ^3.1.0
  go_router: ^17.0.0
  http: ^1.5.0
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_lints: ^6.0.0
  build_runner: ^2.10.0
  json_serializable: ^6.11.1
  freezed: ^3.2.3

flutter:
  uses-material-design: true
